sudo: false

language: node_js

notifications:
  email: false

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - '[ "${TRAVIS_NODE_VERSION}" == "0.8" -o "${TRAVIS_NODE_VERSION}" == "0.10" ] || npm install -g covert'

script:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" -a "${TRAVIS_NODE_VERSION}" != "0.10" ] || npm test'
  - '[ "${TRAVIS_NODE_VERSION}" == "0.8" -o "${TRAVIS_NODE_VERSION}" == "0.10" ] || npm run coverage'

node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - '4'
  - 'iojs-v1.0.0'
  - 'iojs-v2.0.0'
  - 'iojs-v3.0.0'
  - 'iojs'
